src/objects/Department__c.object
<CustomObject>
    <description>To fill department picklist</description>
    <fields>
        <fullName>Department_Value__c</fullName>
        <label>Department Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
                <color>#F3D904</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>AGS-{000000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Population__c.object
<CustomObject>
    <label>Population</label>
    <nameField>
        <displayFormat>Pop-{0}</displayFormat>
        <label>Population ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Population</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeAddExtnController.cls
public with sharing class EmployeeAddExtnController{
    private Employee__c emp;
    
    public string DeptCode {get; set;}
    
    
    // The extension constructor initializes the private member
    // variable acct by using the getRecord method from the standard controller.
    public EmployeeAddExtnController(ApexPages.StandardController stdController) {
        emp = new Employee__c();     
    }
    
    public Employee__C getEmp() {
        return emp;
    }
    
    public List<SelectOption> getDeptPicklist()
    {   
        List<SelectOption> options = new List<SelectOption>();
        List<Department__c> departments= [ Select Name,Department_Value__c From  Department__c Limit 100];
    
        options.add(new SelectOption('',''));
        
        for(Department__c d: departments){
            options.add(new SelectOption(d.Name, d.Department_Value__c ));
        }
            
        return options;
    }  
    
    public PageReference Save()
    {      
    
        
        delete [Select Id from Population__c where Name Like 'Pop-3%' Limit 9000];            
        
        Savepoint sp = Database.setSavepoint(); 
        
        try
        {
            insert emp;              
        }
        catch(Exception ex)
        {
            Database.rollback(sp); 
            emp= emp.clone(false);  
                
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR,
            'An error occured while inserting Employee record.' + ex.getMessage());
            ApexPages.addMessage(errMsg);
            
            return null;
        }  
              
        return null;
    }
    
    public PageReference WebServiceCall()
    {
        try
        {
            system.debug('**********web service call start**********');            
             //Create web service stub
            wwwW3schoolsComWebservices.TempConvertSoap stub= new wwwW3schoolsComWebservices.TempConvertSoap();            
            //stub.endpoint_x = 'http://dummyendpoint.asmx';            
            //Call web service method and hold return value
            string outValue= stub.CelsiusToFahrenheit('10');            
            system.debug('**********Return Value from web service: ' + outValue + '**********');    
        }
        catch(Exception ex)
        {
            emp= emp.clone(false);
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An error occurred while sending Employee record. ' 
            + '\n' + 'Error Message: ' + ex.getMessage());
            ApexPages.addMessage(errMsg);
            
            return null;
        }
            
        return (new ApexPages.Standardcontroller(emp)).view();
    }

}