src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>AGS-{000000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeControllerExtn1.cls
public with sharing class EmployeeControllerExtn1 {
    private final Employee__c emp;
    
    // The extension constructor initializes the private member
    // variable acct by using the getRecord method from the standard
    // controller.
    public EmployeeControllerExtn1(ApexPages.StandardController stdController) {
        stdController.addFields(new String[]{
            'Name',
            'First_Name__c',
            'Id'
        });
        this.emp = (Employee__c)stdController.getRecord();
    }

    public String getGreeting() {
        return 'Hello ' + emp.First_Name__c + ' (' + emp.id + ')';
    }
}