src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>AGS-{000000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeCustomUpdateController.cls
public with sharing class EmployeeCustomUpdateController {

    private final Employee__C emp;

    public EmployeeCustomUpdateController() {
        emp = [SELECT Id, Name, First_Name__c, Last_Name__c FROM Employee__C 
                   WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
    }

    public Employee__C getEmp() {
        return emp;
    }

    public PageReference save() {
        update emp;
        return null;
    }
}