src/objects/Temp_Conversion__c.object
<CustomObject>
    <fields>
        <fullName>Celcius_Temp__c</fullName>
        <label>Celcius Temperature</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fahrenheit_Temperature__c</fullName>
        <label>Fahrenheit Temperature</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Temp Conversion</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Temp Conversion ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temp Conversions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TempConvertWebService.cls
public class TempConvertWebService
{
    @future (callout=true)
    public static void callTempConvertWebService(string inputValue)
    {
        try
        {
            System.debug( 'Received Input' + inputValue ) ;
            
            Temp_Conversion__c obj=new Temp_Conversion__c();
            obj = [select Celcius_Temp__c,Fahrenheit_Temperature__c from Temp_Conversion__c where id=: inputValue];
            
            //Create web service stub
            wwwW3schoolsComWebservices.TempConvertSoap stub= new wwwW3schoolsComWebservices.TempConvertSoap();
            
            //Call web service method and hold return value
            string outValue= stub.CelsiusToFahrenheit(String.valueOf(obj.Celcius_Temp__c));
            
            //Update return value and persist to database
            obj.Fahrenheit_Temperature__c = Decimal.valueOf(outValue);
            update obj;    
        }
        catch(System.AsyncException e)
        { 
            System.debug( '****Exception' +e ) ;
        }
    }
}